matrix:
  include:
    # - os: osx
    #   language: cpp
    #   osx_image: xcode9.3
    #   sudo: required
    #   env: BUILD_TARGET=ios_build
    - os: linux
      language: cpp
      sudo: required
      env: BUILD_TARGET=android_game12
    - os: linux
      language: cpp
      sudo: required
      env: BUILD_TARGET=android_lib
    - os: linux
      language: cpp
      sudo: required
      env: BUILD_TARGET=linux
    - os: osx
      language: cpp
      osx_image: xcode9.3
      sudo: required
      env: BUILD_TARGET=osx

script:
- tools/travis-scripts/run-script.sh
before_install:
- tools/travis-scripts/before-install.sh

cache:
  bundler: true
